Repository Bloomstack/erpnext, pull requests merged in 2021-05, with the labels that each got.

#1198 fix: change batch field in SLE to link field
  erpnext/stock/doctype/batch/batch.json
  erpnext/stock/doctype/stock_ledger_entry/stock_ledger_entry.json
Labels: Needs testing

#1270 fix: duplicate role expense moudule issue fixed
  erpnext/setup/setup_wizard/operations/install_fixtures.py
Labels: hotfix

#1293 chore: Made customer field mandatory for Sales Invoice
  erpnext/accounts/doctype/sales_invoice/sales_invoice.json
Labels: Don't Merge, Test Cases Needed

#1308 fix: leave allocation dashboard shows wrong total allocated leaves issue fixed
  erpnext/hr/doctype/leave_application/leave_application.py
Labels: hotfix

#1300 fix: index error fixed for item_alternative query
  erpnext/patches/v13_0/update_autoname_for_item_alternative.py
  erpnext/stock/doctype/item_alternative/item_alternative.json
  erpnext/stock/doctype/item_alternative/item_alternative.py
Labels: hotfix

#1312 fix: server error fixed, employee autoname fixed, contract move from bloomstack_core to erpnext
  erpnext/crm/doctype/contract/contract.js
  erpnext/crm/doctype/contract/contract.json
  erpnext/crm/doctype/contract/contract.py
  erpnext/crm/doctype/contract/contract_calendar.js
  erpnext/crm/doctype/contract/contract_dashboard.py
Labels: hotfix

#1313 chore: minor change added to aurthorization request method name
  erpnext/crm/doctype/contract/contract.js
  erpnext/utils.py
Labels: hotfix

#1326 fix: contact_display shows wrong info issue fixed
  erpnext/shopping_cart/cart.py
Labels: hotfix
