Repository Bloomstack/erpnext, pull requests merged in 2021-09, with the labels that each got.

#1588 fix: move plant additive log custom fields to core from bloomstack_core
  erpnext/agriculture/doctype/plant_additive_log/plant_additive_log.json
Labels: Merge Bloomstack Core

#1586 fix: move harvest custom fields to core from bloomstack_core
  erpnext/agriculture/doctype/harvest/harvest.json
Labels: Merge Bloomstack Core

#1585 fix: merge employee custom field from bloomstack_core to core
  erpnext/hr/doctype/employee/employee.json
Labels: Merge Bloomstack Core

#1583 fix: move stock_entry_detail custom fields to core from bloomstack_core
  erpnext/stock/doctype/stock_entry_detail/stock_entry_detail.json
Labels: Merge Bloomstack Core

#1571 chore: added custom delivery_settings fields into core from bloomstack_core
  erpnext/stock/doctype/delivery_settings/delivery_settings.json
Labels: Merge Bloomstack Core

#1570 chore: added licenses and opening date fields to Customer
  erpnext/selling/doctype/customer/customer.json
Labels: Merge Bloomstack Core

#1569 chore: added company field in Compliance Info from bloomstack_core
  erpnext/compliance/doctype/compliance_info/compliance_info.json
Labels: Merge Bloomstack Core

#1568 chore: add field item group in batch from bloomstack_core
  erpnext/stock/doctype/batch/batch.json
Labels: Merge Bloomstack Core

#1567 fix: moved billable field of project template task from bloomstack co…
  erpnext/projects/doctype/project_template_task/project_template_task.json
Labels: Merge Bloomstack Core

#1566 chore: merge driver field blm_core to erp
  erpnext/hr/doctype/driver/driver.json
Labels: Merge Bloomstack Core

#1564 fix: move purchase-order-item custom fields to core from bloomstack_core
  erpnext/buying/doctype/purchase_order_item/purchase_order_item.json
Labels: Merge Bloomstack Core

#1596 chore: move timesheet_detail custom fields from bloomstack_core to core
  erpnext/projects/doctype/timesheet_detail/timesheet_detail.json
Labels: Merge Bloomstack Core

#1591 chore: move timesheet custom fields from bloomstack_core to core
  erpnext/projects/doctype/timesheet/timesheet.json
Labels: Merge Bloomstack Core

#1590 chore: move pick_list_item custom fields from bloomstack_core to core
  erpnext/stock/doctype/pick_list_item/pick_list_item.json
Labels: Merge Bloomstack Core

#1589 fix: merge item custom fields blm_core to erp
  erpnext/stock/doctype/item/item.json
Labels: Merge Bloomstack Core

#1595 fix: move purchase order custom fields to core from bloomstack_core
  erpnext/buying/doctype/purchase_order/purchase_order.json
Labels: Merge Bloomstack Core

#1605 fix: merge plant custom field blom_core to erp
  erpnext/agriculture/doctype/plant/plant.json
Labels: Merge Bloomstack Core

#1604 fix: merge plant batch cutom fields blom_core to erp
  erpnext/agriculture/doctype/plant_batch/plant_batch.json
Labels: Merge Bloomstack Core

#1597 fix: move sales order custom fields to erpnext from bloomstack-core
  erpnext/selling/doctype/sales_order/sales_order.json
Labels: Merge Bloomstack Core

#1592 fix: move purchase invoice custom fields to erpnext from bloomstack-core
  erpnext/accounts/doctype/purchase_invoice/purchase_invoice.json
Labels: Merge Bloomstack Core

#1611 chore: move Purchase Receipt custom fields from bloomstack_core to erpnext
  erpnext/stock/doctype/purchase_receipt/purchase_receipt.json
Labels: Merge Bloomstack Core

#1616 chore: move custom fields of Supplier from bloomstack_core to erpnext
  erpnext/buying/doctype/supplier/supplier.json
Labels: Merge Bloomstack Core

#1594 chore: move custom field of quotation from bloomstack_core to erpnext
  erpnext/selling/doctype/quotation/quotation.json
Labels: Merge Bloomstack Core

#1637 chore: Changed the module of "Purchase Receipt" print format from "Bloomstack Core" to "Stock"
  erpnext/stock/print_format/purchase_receipt/__init__.py
  erpnext/stock/print_format/purchase_receipt/purchase_receipt.json
Labels: Merge Bloomstack Core

#1635 fix: merge employee directory report blom_core to erp
  erpnext/hr/report/employee_directory/__init__.py
  erpnext/hr/report/employee_directory/employee_directory.json
Labels: Merge Bloomstack Core

#1634 fix: merge pending Deliveries report blom_core to erp
  erpnext/stock/report/pending_deliveries/__init__.py
  erpnext/stock/report/pending_deliveries/pending_deliveries.js
  erpnext/stock/report/pending_deliveries/pending_deliveries.json
Labels: Merge Bloomstack Core

#1633 chore: moved footer_powered and google_maps_embed html files to erpnext from bloomstack_core
  erpnext/templates/includes/footer/footer_powered.html
  erpnext/templates/includes/google_maps_embed.html
Labels: Merge Bloomstack Core

#1632 chore: move email templates to erpnext from bloomstack_core
  erpnext/templates/emails/authorization_request.html
  erpnext/templates/emails/email_footer.html
  erpnext/templates/emails/new_user.html
Labels: Merge Bloomstack Core

#1647 chore: move api_request_log doctype from bloomstack_Core to erpnext
  erpnext/compliance/doctype/api_request_log/__init__.py
  erpnext/compliance/doctype/api_request_log/api_request_log.js
  erpnext/compliance/doctype/api_request_log/api_request_log.json
  erpnext/compliance/doctype/api_request_log/api_request_log.py
  erpnext/compliance/doctype/api_request_log/test_api_request_log.py
Labels: Merge Bloomstack Core

#1629 chore: Changed the module of "Pick List" print format from "Bloomstack Core" to "Stock"
  erpnext/stock/print_format/pick_list/pick_list.json
Labels: Merge Bloomstack Core

#1628 chore: Changed the module of "Cheque with remittance" print format from "Bloomstack Core" to "Accounts"
  erpnext/accounts/print_format/cheque_with_remittance/__init__.py
  erpnext/accounts/print_format/cheque_with_remittance/cheque_with_remittance.json
Labels: Merge Bloomstack Core

#1627 chore: Changed module of "Web Contract" print format from "Bloomstack Core" to "CRM"
  erpnext/crm/print_format/__init__.py
  erpnext/crm/print_format/web_contract/__init__.py
  erpnext/crm/print_format/web_contract/web_contract.json
Labels: Merge Bloomstack Core

#1626 fix: merge employee information report blom_core to erp
  erpnext/hr/report/employee_information/employee_information.json
Labels: Merge Bloomstack Core

#1625 fix: merge employee checkin report blom_core to erp
  erpnext/hr/report/employee_checkin_report/__init__.py
  erpnext/hr/report/employee_checkin_report/employee_checkin_report.json
Labels: Merge Bloomstack Core

#1624 fix: move customer.py code to erpnext from bloomstack_core
  erpnext/selling/doctype/customer/customer.py
Labels: Merge Bloomstack Core

#1623 chore: Changed module of "Purchase Invoice" print format from "Bloomstack Core" to "Accounts"
  erpnext/accounts/print_format/purchase_invoice/__init__.py
  erpnext/accounts/print_format/purchase_invoice/purchase_invoice.json
Labels: Merge Bloomstack Core

#1650 fix: move driver.py code to erpnext from bloomstack_core
  erpnext/hr/doctype/driver/driver.py
Labels: Merge Bloomstack Core

#1644 chore: moved complaince and bloomtrace utilities code from bloomstack_core to erpnext
  erpnext/compliance/doctype/compliance_settings/compliance_settings.js
  erpnext/compliance/utils.py
Labels: Merge Bloomstack Core, Not Tested

#1654 chore: Move python-metrc from bloomstack_core to erpnext
  requirements.txt
Labels: Merge Bloomstack Core

#1657 chore: code of lead.js file is moved from bloomstack_core to erpnext
  erpnext/crm/doctype/lead/lead.js
Labels: Merge Bloomstack Core

#1655 chore: moved delivery_trip_list.js file code to erpnext file
  erpnext/stock/doctype/delivery_trip/delivery_trip_list.js
Labels: Merge Bloomstack Core

#1652 chore: move authorization_request doctype from bloomstack_core to erpnext
  erpnext/setup/doctype/authorization_request/__init__.py
  erpnext/setup/doctype/authorization_request/authorization_request.js
  erpnext/setup/doctype/authorization_request/authorization_request.json
  erpnext/setup/doctype/authorization_request/authorization_request.py
  erpnext/setup/doctype/authorization_request/test_authorization_request.py
Labels: Merge Bloomstack Core

#1651 chore: boot file functions moved to boot file in erpnext
  erpnext/public/images/desk.png
  erpnext/startup/boot.py
Labels: Merge Bloomstack Core

#1643 chore: Move bloomstack core utils.py function to erpnext apps
  erpnext/setup/utils.py
  erpnext/stock/utils.py
  erpnext/utils.py
Labels: Merge Bloomstack Core

#1631 chore: move lead.py code to erpnext from bloomstack_core
  erpnext/crm/doctype/lead/lead.json
  erpnext/crm/doctype/lead/lead.py
  erpnext/hooks.py
Labels: Merge Bloomstack Core

#1619 chore: delivery_note.js file from bloomstack_core to erpnext
  erpnext/stock/doctype/delivery_note/delivery_note.js
Labels: Merge Bloomstack Core

#1617 chore: move sales_order.js file from bloomstack_core into erpnext
  erpnext/selling/doctype/sales_order/sales_order.js
Labels: Merge Bloomstack Core

#1615 chore: move production_plan.js file from bloomstack_core to erpnext.
  erpnext/manufacturing/doctype/production_plan/production_plan.js
Labels: Merge Bloomstack Core

#1621 chore: move purchase_invoice_list.js file from bloomstack_core into erpnext
  erpnext/accounts/doctype/purchase_invoice/purchase_invoice_list.js
Labels: Merge Bloomstack Core

#1620 chore: move issues.js file from bloomstack_core into erpnext
  erpnext/support/web_form/issues/issues.js
Labels: Merge Bloomstack Core

#1614 chore: move driver.js file from bloomstack_core to erpnext
  erpnext/hr/doctype/driver/driver.js
Labels: Merge Bloomstack Core

#1618 chore: move batch.js file from bloomstack_core into erpnext
  erpnext/stock/doctype/batch/batch.js
Labels: Merge Bloomstack Core

#1662 chore: move bloomtrace.py and compliance.py code to erpnext from bloomstack_core
  erpnext/compliance/doctype/compliance_info/compliance_info.py
  erpnext/compliance/utils.py
Labels: Merge Bloomstack Core

#1661 chore: move accept_payment_request.html file to erpnext from bloomstack_core
  erpnext/www/accept_payment_request.html
Labels: Merge Bloomstack Core

#1656 feat: update Task status based on the default project's status in the Projects child table
  erpnext/projects/doctype/task/task.json
  erpnext/projects/doctype/task/task.py
Labels: hotfix

#1646 chore: move stock_entry.js file to erpnext from bloomstack_core
  erpnext/stock/doctype/stock_entry/stock_entry.js
Labels: Merge Bloomstack Core

#1638 chore: move driver collection report from bloomstack_core to erpnext
  erpnext/hr/report/driver_collection/__init__.py
  erpnext/hr/report/driver_collection/driver_collection.js
  erpnext/hr/report/driver_collection/driver_collection.json
  erpnext/hr/report/driver_collection/driver_collection.py
Labels: Merge Bloomstack Core

#1613 chore: move conf.js file to erpnext from bloomstack_core
  erpnext/public/js/conf.js
Labels: Merge Bloomstack Core

#1678 chore: move plant-additive-log.py code to erpnext from bloomstack_core
  erpnext/agriculture/doctype/plant_additive_log/plant_additive_log.py
  erpnext/hooks.py
Labels: Merge Bloomstack Core

#1675 chore: move stock_entry.py code to erpnext from bloomstack_core
  erpnext/hooks.py
  erpnext/stock/doctype/stock_entry/stock_entry.py
Labels: Merge Bloomstack Core

#1679 chore: move stock_reconciliation.py code to erpnext from bloomstack_core
  erpnext/hooks.py
  erpnext/stock/doctype/stock_reconciliation/stock_reconciliation.py
Labels: Merge Bloomstack Core

#1673 chore: move harvest.py code to erpnext from bloomstack_core
  erpnext/agriculture/doctype/harvest/harvest.py
  erpnext/hooks.py
Labels: Merge Bloomstack Core

#1683 chore: move strain.py code to erpnext from bloomstack_core
  erpnext/agriculture/doctype/strain/strain.py
  erpnext/hooks.py
Labels: Merge Bloomstack Core

#1682 chore: move plant_batch.py code to erpnext from bloomstack_core
  erpnext/agriculture/doctype/plant_batch/plant_batch.py
  erpnext/hooks.py
Labels: Merge Bloomstack Core

#1671 chore: move admin.html file to erpnext from bloomstack_core
  erpnext/www/admin.html
Labels: Merge Bloomstack Core

#1667 chore: move accept_payment_request.py file to erpnext from bloomstack_core
  erpnext/www/accept_payment_request.py
Labels: Merge Bloomstack Core

#1663 chore: move plant.py code to erpnext from bloomstack_core
  erpnext/agriculture/doctype/plant/plant.py
  erpnext/hooks.py
Labels: Merge Bloomstack Core

#1660 chore: move sales_invoice_list.js file to erpnext from bloomstack_core
  erpnext/accounts/doctype/sales_invoice/sales_invoice_list.js
Labels: Merge Bloomstack Core

#1659 chore: move authorize_document .py and .html files to erpnext from bloomstack_core
  erpnext/www/authorize_document.html
  erpnext/www/authorize_document.py
Labels: Merge Bloomstack Core

#1658 chore: move quotation.js file code to erpnext from bloomstack_core
  erpnext/selling/doctype/quotation/quotation.js
Labels: Merge Bloomstack Core

#1642 chore: move sign_document.js file from bloomstack_core to erpnext
  erpnext/templates/includes/sign_document.js
Labels: Merge Bloomstack Core

#1686 chore: move item.py code to erpnext from bloomstack_core
  erpnext/hooks.py
  erpnext/stock/doctype/item/item.py
Labels: Merge Bloomstack Core

#1680 chore: move sales-invoice.py code to erpnext from bloomstack_core
  erpnext/accounts/doctype/sales_invoice/sales_invoice.py
Labels: Merge Bloomstack Core

#1665 chore: move delivery_note.py code to erpnext from bloomstack_core
  erpnext/hooks.py
  erpnext/stock/doctype/delivery_note/delivery_note.py
Labels: Merge Bloomstack Core

#1692 chore: moved work_order.js from bloomstack_core to erpnext
  erpnext/manufacturing/doctype/work_order/work_order.js
Labels: Merge Bloomstack Core

#1691 chore: moved work_order_calender.js to erpnext from bloomstack_core
  erpnext/manufacturing/doctype/work_order/work_order_calendar.js
Labels: Merge Bloomstack Core

#1672 chore: move public css file from bloomstack_core to erpnext
  erpnext/public/css/authorize_document.css
  erpnext/public/css/contract.css
  erpnext/public/css/license_search.css
  erpnext/public/css/order_desk.css
  erpnext/public/css/products.css
  erpnext/public/css/reports.css
  erpnext/public/css/track_and_trace.css
Labels: Merge Bloomstack Core

#1641 chore: move item.js code to erpnext from bloomstack_core
  erpnext/stock/doctype/item/item.js
Labels: Merge Bloomstack Core

#1695 chore: moved demo.html from bloomstack_core to erpnext
  erpnext/templates/pages/demo.html
Labels: Merge Bloomstack Core

#1694 chore: move setup_wizard.js to erpnext from bloomstack_core
  erpnext/public/js/setup_wizard.js
Labels: Merge Bloomstack Core

#1702 chore: move setup wizard stages to erpnext from bloomstack_core
  erpnext/setup/setup_wizard/setup_wizard.py
Labels: Merge Bloomstack Core

#1701 chore: move delivery note api to erpnext from bloomstack_core
  erpnext/stock/doctype/delivery_note/delivery_note.py
Labels: Merge Bloomstack Core

#1697 chore: move the license search feature from bloomstack core to erpnext
  erpnext/compliance/page/__init__.py
  erpnext/compliance/page/license_search/__init__.py
  erpnext/compliance/page/license_search/license_search.css
  erpnext/compliance/page/license_search/license_search.js
  erpnext/compliance/page/license_search/license_search.json
  erpnext/compliance/page/license_search/license_search.py
  erpnext/erpnext_integrations/page/__init__.py
Labels: Merge Bloomstack Core

#1705 chore: move purchase_order_list.js file to erpnext from bloomstack_core
  erpnext/buying/doctype/purchase_order/purchase_order_list.js
Labels: Merge Bloomstack Core

#1704 fix:added the files to hooks.py or build.json
  erpnext/hooks.py
  erpnext/public/build.json
  erpnext/public/css/license_search.css
Labels: Merge Bloomstack Core

#1706 fix: circular import for get_bank_cash_account
  erpnext/stock/doctype/delivery_note/delivery_note.py
  erpnext/stock/doctype/delivery_trip/delivery_trip.py
Labels: Merge Bloomstack Core
