Repository Bloomstack/erpnext, pull requests merged in 2021-08, with the labels that each got.

#1347 feat: automated configurable status updater added
  erpnext/accounts/doctype/bank_transaction/bank_transaction.json
  erpnext/buying/doctype/purchase_order/purchase_order.json
  erpnext/controllers/status_updater.py
  erpnext/crm/doctype/lead/lead.json
  erpnext/crm/doctype/opportunity/opportunity.json
  erpnext/patches.txt
  erpnext/patches/v13_0/add_status_and_status_workflow.py
  erpnext/selling/doctype/quotation/quotation.json
  erpnext/selling/doctype/sales_order/sales_order.json
  erpnext/setup/setup_wizard/data/status.json
  erpnext/setup/setup_wizard/data/status_workflow.json
  erpnext/setup/setup_wizard/operations/install_fixtures.py
  erpnext/stock/doctype/delivery_note/delivery_note.json
  erpnext/stock/doctype/material_request/material_request.json
  erpnext/stock/doctype/purchase_receipt/purchase_receipt.json
Labels: Depends on Frappe

#1536 fix: fixed pick-list module test case
  erpnext/stock/doctype/pick_list/test_pick_list.py
Labels: Test Case PR

#1535 chore: creates email queue for each email group member in email campaign
  erpnext/crm/doctype/email_campaign/email_campaign.py
Labels: hotfix
